### ISSUE TITLE
Unclear documentation for rich push

### ISSUE THREAD

**Issue by AdamGerthel** [customerio/customerio-expo-plugin#128]
The [documentation for setting up rich push](https://customer.io/docs/sdk/expo/getting-started/#rich-push-setup) for managed projects suggests adding the following app config:

```javascript
 "build": {
    "experimental": {
       "ios": {
          "appExtensions": [{
             "targetName": "NotificationService",
             "bundleIdentifier": "${appIdentifier}.richpush",
          }],
       },
    },
 },
```
But there's no mention of *where* this config goes. `ExpoConfig` doesn't have a `build` property. IIRC, it used to, but it was moved to a separate package, `'expo-build-properties'`. Is that where this config should be? And if so, exactly in which format? Because I'm not sure if the `experimental` prop exists there.

**Comment by mrehan27** [comment]
Thanks for reaching out and sharing your concern. I've shared your feedback internally, and we'll be updating our documentation soon to help minimize any confusion.

For your question, this configuration needs to be set in the `app.json` file, specifically under `expo -> extra -> eas -> build -> experimental -> ios -> appExtensions`. You can find more details on this in the [Expo documentation](https://docs.expo.dev/build-reference/app-extensions/).

Let me know if you need further help or have more questions. Please feel free to reach out anytime.

**Comment by erickreutz** [comment]
This information is very difficult to find in the docs because it's buried in the 1.0 version docs and does not surface in he current (2.0) version of the docs.
