### ISSUE TITLE
Push notif message not displayed an android, when deeplink is added

### ISSUE THREAD

**Issue by Samox** [customerio/customerio-expo-plugin#134]
Hello,
When I add a deeplink on the push notification, on android I only see the title of the notif, the message does not appear.
If I remove the deeplink, it works well.

I have tested it on on OPPO and One Plus 6, on android 13. 
It works perfectly on ios though.

```   
  "customerio-expo-plugin": "^1.0.0-beta.15",
  "customerio-reactnative": "^3.5.2",
  "expo": "^50.0.14",
```

Do you know how I could debug this ?

**Comment by Shahroz16** [comment]
Hey @Samox, thank you for reaching out can you please provide more information on how you are sending push notifications, and what the payload looks like?

**Comment by Samox** [comment]
I use the standard push notif. 

![CleanShot 2024-03-29 at 18 00 15@2x](https://github.com/customerio/customerio-expo-plugin/assets/6906559/dda6c279-d2e4-41f2-8c6e-b22923213f64)

And when I add the deeplink, the notif is displayed like this 
![CleanShot 2024-03-29 at 18 04 26@2x](https://github.com/customerio/customerio-expo-plugin/assets/6906559/4d09193b-f659-4eda-a19d-aa56af447105)

(also, sometimes during my test, the first time I send a pushnotif, the body is not displayed, then on the second test it is displayed. But I cannot reproduced consistently. When I add the deeplink though there is always the bug)

**Comment by Shahroz16** [comment]
@Samox thanks for providing more details, are you using any other push services in your application?

**Comment by Samox** [comment]
Yes, we use intercom as well 😬

**Comment by Shahroz16** [comment]
That must be it! You can find more about how to handle multiple push services [here](https://www.customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#how-to-handle-multiple-push-providers). 

If you want to go with option 2, use `android.setHighPriorityPushHandler` it's in the [config in Expo SDK](https://www.customer.io/docs/sdk/expo/getting-started/#configure-the-plugin) that you can utilize.

**Comment by Samox** [comment]
Option 2 works like a charm !
I completely missed that [documentation](https://www.customer.io/docs/sdk/react-native/push-notifications/multiple-push-providers/#how-to-handle-multiple-push-providers). It would be nice in the [Expo Getting Started](https://customer.io/docs/sdk/expo/getting-started/) as well :)

**Comment by Shahroz16** [comment]
Awesome, noted the recommendation as well.
