### ISSUE TITLE
[iOS] - Testflight warning - ITMS-91053: Missing API declaration 

### ISSUE THREAD

**Issue by umangloria** [customerio/customerio-expo-plugin#137]
Getting this mail from apple with each new build submission to testflight.

`ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/NotificationService.appex/NotificationService” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.`

There is ongoing issue on Expo's github and this reply actually seems helpful: https://github.com/expo/expo/issues/27796#issuecomment-2043222184

**Comment by levibostian** [comment]
Thanks for sending this to us. Especially the Expo issue link. Very helpful, thank you! 

The latest versions of our SDKs and Expo plugin do not currently have privacy manifest files included in them. This is probably why you are seeing this message. 

We are in the process of releasing a new version of our React Native SDK that will include these privacy manifest files. Follow [this issue](https://github.com/customerio/customerio-reactnative/issues/248) to watch progress of us releasing this. 

After our new React Native SDK releases, install it into your app and try another TestFlight upload to see if you continue to receive this error.

**Comment by levibostian** [comment]
The latest React Native SDK contains the new privacy manifest files! 

Install the latest version of the React Native SDK, 3.6.0, in your app. Be sure to run `expo prebuild --clean` after you update the npm packages. 

Give it a try and let us know if you encounter problems along the way.
