### ISSUE TITLE
"encountered already present delegate" warning when using with Expo Push Notifications

### ISSUE THREAD

**Issue by lucaventura** [customerio/customerio-expo-plugin#144]
When using this plugin in combination with `expo-notifications` our expo push notifications no longer work, and we receive this warning:

`[expo-notifications] EXNotificationCenterDelegate encountered already present delegate of UNUserNotificationCenter: <CioMessagingPush.UserNotificationsFrameworkAdapterImpl: 0x301998910>. EXNotificationCenterDelegate will not overwrite the value not to break other features of your app. In return, expo-notifications may not work properly. To fix this problem either remove setting of the second delegate or set the delegate to an instance of EXNotificationCenterDelegate manually afterwards.`

Using these package versions:

`"customerio-expo-plugin": "^1.0.0-beta.15",
    "customerio-reactnative": "^3.8.0",
    "expo": "~50.0.19",
"expo-notifications": "~0.27.8",`

**Comment by levibostian** [comment]
Hey there, Luca. Thank you for all of the details provided thus far. Sorry to hear you're experiencing this issue. Let me try and help get this resolved. 

As far as the warning message, it's one that can be ignored. We have taken extra steps to verify that the Customer.io Expo plugin and `expo-notifications` is compatible together so even though you see a warning, the Customer.io expo plugin generates code that satisfies the requirements stated by this warning message. 

Could you describe what is no longer working for you? Could you describe the expected and actual behavior? Could you give a series of steps that you perform in your app to reproduce the behavior? 

Hope you have a wonderful day!

**Comment by lucaventura** [comment]
After adding the `customerio-expo-plugin` our calls to `Notifications.getExpoPushTokenAsync()` no longer resolve, they hang indefinitely. If we remove the  `customerio-expo-plugin` the issue does not happen.

**Comment by levibostian** [comment]
Sorry again to hear that you are experiencing this behavior. 

We are aware of `Notifications.getExpoPushTokenAsync()` calls not resolving after adding the Customer.io Expo plugin. This issue is being tracked in [this issue](https://github.com/customerio/customerio-expo-plugin/issues/131). 

To try and unblock your app, I recommend reading through the comments in that similar issue to see if any of the suggestions work for your app. 

Feel free to share more details if you believe your issue is unrelated and we will be happy to re-open it.

**Comment by AndranikT** [comment]
any one know how to resolve this issue.. I use sdk 53 and again met with this issue, on android platforms working correct but on ios  doesn't resolve nor reject . but in build profile  some times age like 3 days is correct working on ios development mode, but now not.. 

  const pushTokenString = await Notifications.getExpoPushTokenAsync({ projectId: "f203794b-af10-42ab-83e4-825442d4b84e" })
            if (!pushTokenString?.data) {
                Alert.alert("No token", JSON.stringify(pushTokenString));
            } else {
                Alert.alert("Push Token", pushTokenString.data);
            }

            console.log("Register Push Token :",pushTokenString.data);
            return pushTokenString.data;
