### ISSUE TITLE
Add options for adding notification badges

### ISSUE THREAD

**Issue by Nikit-Singh** [customerio/customerio-expo-plugin#149]
Hey team, I was wondering if you could please add an option to add notification badges to the expo plugin since doing that currently is not very straightforward.

**Comment by ami-aman** [comment]
Hi @Nikit-Singh 

Thank you for creating the issue, it sound more like a feature request. I have a few questions before moving forward with it:

- Some of our customers manage notification badges by sending specific values in the payload for iOS. For example, you can set the badge count using a notification payload like this:

```json
{
  "aps": {
    "alert": {
      "title": "New Message",
      "body": "You have a new message."
    },
    "badge": 5
  }
}
```

- On Expo plugin, is this request for iOS, Android, or both platforms?

- Additionally, is there any specific use case or further details you'd like to share with us so we can have a clearer understanding of your requirements?

- What specific behaviour are you expecting from the feature ? Are you looking to control the badge counts programmatically or do you need flexibility in how badges are updated or displayed ?

- Are you implementing the badges currently in your app ? If yes, how do you manage that ?

**Comment by Nikit-Singh** [comment]
* On Expo plugin, is this request for iOS, Android, or both platforms?
  + It's for iOS
* Additionally, is there any specific use case or further details you'd like to share with us so we can have a clearer understanding of your requirements?
  + Is there a way to clear the notification received using the payload above when opening the app?
* What specific behaviour are you expecting from the feature ? Are you looking to control the badge counts programmatically or do you need flexibility in how badges are updated or displayed ?
  + Only a way to clear notification is required as of now by us when opening the app from a killed state or the background state.
* Are you implementing the badges currently in your app ? If yes, how do you manage that ?
  + No

**Comment by ami-aman** [comment]
Hi @Nikit-Singh ,

Thanks for the clarification.

Based on your use case, I would recommend setting the badge value to 0 directly in the push payload. For example:
```
{
  "aps": {
    "alert": {
      "title": "New Message",
      "body": "You have a new message."
    },
    "badge": 0
  }
}
```

 This will reset or remove the badge when the app is opened, whether from a killed state or background state. Including "badge": 0 in the push notification payload will help you achieve this, and the badge count will be cleared automatically.

Let me know if you have any further questions or need additional assistance with this!

**Comment by Nikit-Singh** [comment]
I don't want to hide the badge by sending a new notification. I want to do it when the user opens the app. This doesn't seems to be the proper way to do that.
