### ISSUE TITLE
Version 1.0.0-beta.15 not compatible with "customerio-reactnative": "4.0.1" on IOS

### ISSUE THREAD

**Issue by AChevallier** [customerio/customerio-expo-plugin#153]
Hello !

I wanted to upgrade my app expo with "customerio-reactnative": "4.0.1".
But it seems that the current version of customerio-expo-plugin is not compatible with "customerio-reactnative": "4.0.1" on IOS

Here the error
```
[RUN_FASTLANE] ▸ ** BUILD FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸        SwiftEmitModule normal x86_64 Emitting\ module\ for\ NotificationService (in target 'NotificationService' from project 'XXXXX')
[RUN_FASTLANE] ▸        SwiftCompile normal x86_64 /var/folders/jr/vzf29l0n5sl24_9mjl93p7pm0000gn/T/eas-build-local-nodejs/4ba72d39-d211-4bb6-9d12-c7f32cf6fd09/build/apps/XXXXX/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'XXXXX')
[RUN_FASTLANE] ▸        SwiftCompile normal x86_64 Compiling\ NotificationService.swift /var/folders/jr/vzf29l0n5sl24_9mjl93p7pm0000gn/T/eas-build-local-nodejs/4ba72d39-d211-4bb6-9d12-c7f32cf6fd09/build/apps/XXXXX/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'XXXXX')
[RUN_FASTLANE] ▸        SwiftCompile normal x86_64 Compiling\ Env.swift /var/folders/jr/vzf29l0n5sl24_9mjl93p7pm0000gn/T/eas-build-local-nodejs/4ba72d39-d211-4bb6-9d12-c7f32cf6fd09/build/apps/XXXXX/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'XXXXX')
[RUN_FASTLANE] ▸        SwiftCompile normal x86_64 /var/folders/jr/vzf29l0n5sl24_9mjl93p7pm0000gn/T/eas-build-local-nodejs/4ba72d39-d211-4bb6-9d12-c7f32cf6fd09/build/apps/XXXXX/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'XXXXX')
[RUN_FASTLANE] ▸ (5 failures)
[RUN_FASTLANE] Exit status: 65
```

The build is working well with the version 3.9.0

**Comment by ami-aman** [comment]
Hey there ! 

Thank you for your interest in adopting the latest React Native version, which now supports Customer.io Data Pipelines (CDP). Unfortunately, we do not currently support `customerio-reactnative` version `4.0.1` with our Expo plugin. You can find more information about this in our [documentation](https://docs.customer.io/sdk/expo/getting-started/#install).

We are actively working on adding support for CDP in Expo, but we do not have a specific timeline to share at the moment. Rest assured, we will notify you once CDP support is available in our Expo plugin. In the meantime, we recommend continuing to use `customerio-reactnative version` `3.9.1` or earlier.

I will go ahead and close this issue for now but feel free to reopen or drop a comment if you have any queries.
