### ISSUE TITLE
InApp Messages dismissal leaves app unresposive

### ISSUE THREAD

**Issue by rafael-urena-yoke** [customerio/customerio-expo-plugin#157]
In app messages work correctly until dismissed, they go away correctly but the app becomes unresponsive to touch events after. Not even the expo inspector is clickable after dismissing the inApp message and to make it work again we have to close and open the app.

We are using the following versions:

```
 "customerio-expo-plugin": "^1.0.0-beta.15",
 "customerio-reactnative": "^3.7.0",

```

with expo sdk-51.

I've tested with versions beta-16 of the plugin and also tried previous versions of the main package, as well as 3.9.1. So it seems this issue isn't version specific. 

Any thoughts on what could be going on here?

**Comment by Shahroz16** [comment]
Hey @rafael-urena-yoke, thank you for reaching out. 

Can you please [share the logs](https://docs.customer.io/sdk/expo/updates-and-troubleshooting/troubleshooting/) to [win@customer.io](mailto:win@customer.io) along with a link to the in-app message in [Customer.io](http://customer.io/) that you're using to test.
