### ISSUE TITLE
Build failing in EAS with version 1.0.0-beta.17/Expo 52

### ISSUE THREAD

**Issue by enaluz** [customerio/customerio-expo-plugin#175]
I ran into this issue because while trying to upgrade to Expo SDK 52, I saw that I also needed to upgrade the customerio dependencies. After I tried to create a build in EAS, I saw the following errors in the xcode logs:

```
Build failed: The "Run fastlane" step failed because of an error in the Xcode build process. We automatically detected following errors in your Xcode build logs:
- unknown type name 'CIOAppPushNotificationsHandler'
- use of undeclared identifier 'CIOAppPushNotificationsHandler'
- unknown type name 'CIOAppPushNotificationsHandler'
- use of undeclared identifier 'CIOAppPushNotificationsHandler'
Refer to "Xcode Logs" below for additional, more detailed logs.
```

**customerio-expo-plugin:** 1.0.0-beta.17
**customerio-reactnative:** 3.9.1
**expo:** 52.0.18

From my `app.config.ts` file:

```
      [
        'expo-build-properties',
        {
          android: {
            buildToolsVersion: '34.0.0',
            compileSdkVersion: 34,
            targetSdkVersion: 34,
          },
          ios: {
            deploymentTarget: '15.1',
             pushNotification: {
              env: {
                apiKey: '<...>',
                region: '<...>',
                siteId: '<...>'
              },
              useRichPush: true,
            },
          },
        },
      ],
```

When I run the cio doctor cli, I get this:

```
Starting diagnostic for React Native project...
[✓] Project Path: <redacted>
[✗] Customer.io React Native SDK not found in package lock file. Make sure to run `yarn install` or `npm install` before running the project.
[!] Customer.io React Native SDK version: 3.7.0
Warning: Update to the latest SDK version 4.1.1

Initialization
[✗] React Native SDK Initialization not found. For more details, run the script with the -v flag
[✓] iOS SDK Initialization found in 'mobile/ios/<redacted>/PushService.swift'

Push Setup
[✓] Push notification capability found in entitlements
[✗] Notification Service Extension (NSE) not found
Error: The Notification Service Extension is required in order to display and track push notifications.
[✓] MessagingPush Initialization found in 'mobile/ios/<redacted>/PushService.swift'

Dependencies
[✓] No conflicting packages found
[✓] No conflicting pods found
[✓] CustomerIOTracking: 2.14.2
[✓] CustomerIOMessagingInApp: 2.14.2
[✓] CustomerIOMessagingPushAPN: 2.14.2

Diagnostic complete!
```

I definitely have the dependencies installed, I'm assuming that cio doctor is being buggy because I'm using an nx monorepo. Dependencies are hoisted.

**Comment by mahmoud-elmorabea** [comment]
Hey, thanks for the report! 

The error seems to suggest that some of the files that are auto generated by our plugin is missing, here are some pointers to troubleshoot the problem:
- Can you check the generated iOS project code to see if `CIOAppPushNotificationsHandler` type is created in a file called `<YourAppName>/ios/<YourIosProject>/PushService.swift`
- Can you please ensure following the [docs for configuring the plugin](https://docs.customer.io/sdk/expo/getting-started/#configure-the-plugin), it seems you might be injecting our plugin config incorrectly
- The plugin should have its own `customerio-expo-plugin` entry in your `app.config.ts` with plugin specific configuration
