### ISSUE TITLE
How to Properly Secure Site ID and API Key

### ISSUE THREAD

**Issue by bryanyan** [customerio/customerio-expo-plugin#28]
In the initialization instructions here: https://customer.io/docs/sdk/expo/getting-started/#initialize-the-sdk, it says the following:

```
In useEffect, initialize the package with your CustomerioConfig options and CustomerIOEnv variables.
You can find your Site ID and API Key credentials—or create new ones
—under Data & Integrations > Integrations > Customer.io API:

useEffect(() => {
   const data = new CustomerioConfig()
   data.logLevel = CioLogLevel.debug

   const env = new CustomerIOEnv()
   env.siteId = Env.siteId
   env.apiKey = Env.apiKey
   env.organizationId = Env.organizationId
   //organizationId is used to send in-app messages.
   env.region = Region.US
   //Region is optional, defaults to Region.US. Use Region.EU for EU-based workspaces.

   CustomerIO.initialize(env, data)
}, [])
```
How do we properly secure the site ID and API key this way? It doesn't seem like this can be added into Expo Secrets, as their [docs](https://docs.expo.dev/build-reference/variables/#using-secrets-in-environment-variables) indicate that Expo secrets is more intended for build jobs. Their warning also says

```
Always remember that anything that is included in your client side code should be considered public and readable
to any individual that can run the application. EAS Secrets are intended to be used to provide values to an
EAS Build job so that they may be used during the build process. Examples of correct usage include setting 
the NPM_TOKEN for installing private packages from npm, or a Sentry API key to create a release and upload 
your sourcemaps to their service. EAS Secrets do not provide any additional security for values that you end up 
embedding in your application itself, such as an AWS access key or other private keys.
```

Wouldn't initializing the CustomerIO env this way be client side and public?

**Comment by xtreem88** [comment]
Hi @bryanyan 
Thank you for reaching out.
Generally, we leave securing the secrets to the users to give them the flexibility to secure them as they wish.
I recommend following the instructions on [React Native docs](https://reactnative.dev/docs/security#secure-storage) to find the most suitable way to secure your secret keys.
