### ISSUE TITLE
Configuring when push notification permissions are requested

### ISSUE THREAD

**Issue by euc-callum** [customerio/customerio-expo-plugin#32]
It appears that there is currently no way to delay the request for push notification permissions and that it is currently set to occur on first launch of the app.

Would it be possible to add configuration to optionally include the `registerPushNotification` function as seen in step 4 of [these docs](https://www.customer.io/docs/sdk/react-native/push/#integrate-push-notifications-in-your-app)?

**Comment by xtreem88** [comment]
Hi @euc-callum 
This feature is currently under development in our React Native SDK and will also be available via our Expo plugin. We hope to release it soon. Thanks!

**Comment by euc-callum** [comment]
Nice! Is there an ETA on this? I'm currently trying to determine whether we utilise Customer.IO or an alternative - and this is one of the inputs into that decision.

**Comment by euc-callum** [comment]
Is this the correct issue to watch in `customerio-reactnative`?

https://github.com/customerio/customerio-reactnative/issues/58

**Comment by xtreem88** [comment]
An option `ios.disableNotificationRegistration` has been added to optionally remove `registerPushNotification`; please see the [docs](https://customer.io/docs/sdk/expo/getting-started/#install) for more.
