### ISSUE TITLE
Adding deeplink to notification doesn't redirect me to a specific screen when app is in killed mode

### ISSUE THREAD

**Issue by vaibhavs2** [customerio/customerio-expo-plugin#48]
Using
    "customerio-expo-plugin": "^1.0.0-beta.3",
    "customerio-reactnative": "^2.0.0-beta.1",
     "expo": "^45.0.0",
     
   Somehow I have enabled rich notification, Now I can send image and deep-link url in notification.
   

1.    When app is in killed mode and notification arrives -> when notification get clicked it is redirecting me to home-screen not to a specific detail-screen that deep-link should be.

2. When app is in background/foreground it is working well, clicking on notification landing me to detail-screen.

Triggering deep linking is automatically handled by CustomerIO SDK right?
 Anything I am missing?
 
 I have tried this [solution](https://github.com/customerio/customerio-reactnative/issues/47#issuecomment-1322431951) as in expo we cannot change native codes, so i have changed ` bitcode: "Release",` and also tried adding custom payload

**Comment by xtreem88** [comment]
@vaibhavs2 Thanks for bringing this to our attention, we are working on a fix to this issue, and it should be part of the next release coming soon. But if you are blocked on this, try applying [this workaround](https://customer.io/docs/sdk/react-native/push/#troubleshoot-ios-deep-links) after running `prebuild`

**Comment by joeyhotz** [comment]
Hello @xtreem88 , any updates on this?
