### ISSUE TITLE
Should `customerio-reactnative` also be installed?

### ISSUE THREAD

**Issue by reichhartd** [customerio/customerio-expo-plugin#50]
The installation documentation does not require `customerio-reactnative` to be installed as a dependency. However, it is listed in the `package.json` as a `peerDependencies`.

Which of these installation steps is the correct one?

**Comment by xtreem88** [comment]
Hi @reichhartd 
I'm sorry for the confusion; the plugin [does require `customerio-reactnative` ](https://customer.io/docs/sdk/expo/getting-started/#install), but please use version 2.0.0 of `customerio-reactnative` for now.

**Comment by jbtheard** [comment]
perhaps that could be somewhere in the docs ?
