### ISSUE TITLE
Issue with customer IOS on ios Expo

### ISSUE THREAD

**Issue by Joshmatjjen** [customerio/customerio-expo-plugin#53]
After setting up all configuration and run Eas Build, Android work fine but IOS build failed with this error: 

[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):
 VendoirDev (true) and NotificationService (false) do not both set use_frameworks!.

app.config.json (config): 

- '@react-native-firebase/app',
      '@react-native-firebase/dynamic-links',
      [
        'expo-build-properties',
        {
          android: {
            compileSdkVersion: 33,
            targetSdkVersion: 32,
            buildToolsVersion: '30.0.2',
          },
          ios: {
            useFrameworks: 'static',
            deploymentTarget: '13.0',
          },
        },
      ],
      [
        'customerio-expo-plugin',
        {
          android: {
            // replace this to './assets/json/google-services-prod.json' before making a prod build
            googleServicesFilePath: './assets/json/google-services-dev.json',
          },
          ios: {
            pushNotification: {
              useRichPush: true,
            },
          },
        },
     ],

**Comment by xtreem88** [comment]
Hi @Joshmatjjen 
The error indicates that your main target sets `use_frameworks' to static; you did this by using `expo-build-properties` and setting `useFrameworks` to `static`
```
ios: {
useFrameworks: 'static',
deploymentTarget: '13.0',
},
```
But `customerio-expo-plugin` creates a new target named `NotificationService` and this does not set `use_frameworks' to static.
You need to set `ios.useFrameworks` to static in your `customerio-expo-plugin` config object to fix the error.
