### ISSUE TITLE
Compatibility with mono repo

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-expo-plugin#60]
While building in the context of a mono repo, I get a build error while running expo prebuild

`Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/PushService.swift to /Users/me/Documents/mymonorepo/apps/myapp/ios/MindDay/PushService.swift:  Error: ENOENT: no such file or directory`

That can be fixed using "no hoist" in package.json but this is an ugly workaround to something that can perhaps be fixed by using proper working directory?

```
"workspaces": {
    "nohoist": [
      "customerio-reactnative",
      "customerio-expo-plugin"
    ]
  }
```

**Comment by xtreem88** [comment]
Hi @jbtheard 

I apologize for the inconvenience; we'll make the necessary changes and push a new release with the fix.

**Comment by levibostian** [comment]
This feature request has been logged internally. Because of that, I will close this issue. 

Anyone can feel free to comment on the issue if they have questions or comments.
