### ISSUE TITLE
Missing env variable Region when building for iOS

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-expo-plugin#61]
I'm trying to build for iOS and I get the following error: 

```
❌  (ios/NotificationService/Env.swift:7:45)

  5 |     static var customerIOSiteId: String = "{{SITE_ID}}"
  6 |     static var customerIOApiKey: String = "{{API_KEY}}"
> 7 |     static var customerIORegion: Region = {{REGION}} // "us" or "eu"
    |                                             ^ cannot find 'REGION' in scope
```

How can I specify Region variable so that it's picked by the build ? I have tried to add it to app.config.ts but that wouldn't change a thing.

**Comment by ami-aman** [comment]
Hi @jbtheard 

Thank you for reaching out. You can specify region in `app.config.ts` or `app.json` as required. If you are using `app.config.ts` then the configuration for env should look like:

```
.
.
ios: {
            pushNotification: {
              useRichPush: true,
              env: {
                  siteId: "someValueForSiteId",
                  apiKey: "someValueForApiKey",
                  region: "US" // change this to EU, if your workspace is in EU region.
               }
       }
 }
.
.
```

For more details, check out our docs [here](https://customer.io/docs/sdk/expo/getting-started/#configure-the-plugin).

**Comment by jbtheard** [comment]
oh I missed that page perhaps you shouldn't have any doc in this repo and only point to the doc on customer.io domain ?

**Comment by jbtheard** [comment]
Just a suggestion here but rather than using specific env key as iOS param, couldn't we reuse the config available to JS ?

**Comment by ami-aman** [comment]
> oh I missed that page perhaps you shouldn't have any doc in this repo and only point to the doc on customer.io domain ?

I see what you are saying @jbtheard ! Sorry for the confusion. I will talk with the team about it and see how best we can handle this case. 


> Just a suggestion here but rather than using specific env key as iOS param, couldn't we reuse the config available to JS ?

I am not sure what you mean by _config available to JS_. Could you help me understand this ?

**Comment by levibostian** [comment]
Closing because it seems the original issue has been resolved. 

Feel free to comment back if this issue still persists.
