### ISSUE TITLE
Add doc for expo-notifications

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-expo-plugin#69]
I'd love to see more doc about coexistence of expo-notifications with that sdk in [this section](https://www.customer.io/docs/sdk/react-native/push/#cio-process-notification-payloads) of your doc

You briefly illustrate with _rnfirebase_ but I guess most of expo users will use expo-notifications indeed.

**Comment by mrehan27** [comment]
Hi @jbtheard. Thanks for reaching out. We haven't yet tested our SDK with expo-notifications. I'm adding your vote to the request so we can notify you once we have tested it and added to our docs.

Meanwhile, if you are using or have used our SDK with expo-notifications, can you please share the feedback or list down any problems you faced with it?

**Comment by jbtheard** [comment]
I'm first trying to figure out how to make customer.io work without expo-notification and then I'll try to add it. But I see some users have reported incompatibilities already

**Comment by zdnk** [comment]
Btw, for now I have tried to disable the automatic device registration for customerio myself, but I think with [this change](https://github.com/veevoystudio/customerio-expo-plugin/commit/e59b25cba56804aae8c696cc5a2b63d84e03675d) I have somehow disabled push notification handling. When we send push notification that has HTTP URL, it does not open the URL, but rather just opens the app.

**Comment by ami-aman** [comment]
@jbtheard I wanted to inform you that we have recently implemented new methods to track push metrics ([react native](https://customer.io/docs/sdk/react-native/push-notifications/push-metrics/#metrics-javascript) and [expo](https://customer.io/docs/sdk/expo/push/#metrics-javascript)), even when utilizing other libraries like expo-notifications. 

Our team is continuously improving our documentation and enhancing the overall customer experience. While we are still working on the documentation, I will proceed with closing this ticket.

Thank you for your efforts and patience. Your support is greatly appreciated!

@zdnk I apologize for any inconvenience caused. Could you please provide more details about the issue either by creating a separate ticket or sending us an email at win@customer.io? This will help us better understand the problem and assist you accordingly. Thank you!
