### ISSUE TITLE
Installation improvement for use_frameworks

### ISSUE THREAD

**Issue by MatiasLjubica** [customerio/customerio-expo-plugin#7]
Hi ! I try to use this plugin to my Expo projet but I having some trouble to install pod dependency because my project also use Analytics and it's require to use the use_framework! tag but it's break the build with this error:

_- Runner (true) and NotificationService (false) do not both set use_frameworks!._

So i add this:
```xml
target 'NotificationService' do
  use_frameworks!
  pod 'CustomerIO/MessagingPushAPN', '~> 1.2.0-alpha.3'
end
```

but it fail because he need to be static, so i use this:
```xml
target 'NotificationService' do
  use_frameworks! :linkage => :static
  pod 'CustomerIO/MessagingPushAPN', '~> 1.2.0-alpha.3'
end
```

and it work !

Can you add an option into the plugin to add this line if the project use use_framework ?

Thank you

**Comment by ami-aman** [comment]
Hi @MatiasLjubica 

I appreciate you asking this feature request in our config plugin. Just to make sure we understand it right, would it be justified to say that the request is to make the plugin configurable such that even static libraries could be linked in iOS using `:linkage => :static` ? Feel free to correct me if I am wrong !

**Comment by xtreem88** [comment]
This feature has been added and released. See https://github.com/customerio/customerio-expo-plugin/pull/9
