### ISSUE TITLE
Incompatibility with Podfile's "use_framework!"

### ISSUE THREAD

**Issue by simontoulouze** [customerio/customerio-expo-plugin#71]
Hi, 

We are trying to integrate customerio on an Expo SDK47 app. 
We also have @react-native-firebase/analytics package which requires the use of the following plugin [according to their doc](https://docs.expo.dev/versions/v47.0.0/sdk/firebase-analytics/#additional-configuration-for-ios)
```
[
  'expo-build-properties',
  {
    ios: {
      useFrameworks: 'static',
    }
  }
]
```

However, whenever I try to build the app with EAS, I get the following error :
```
App (true) and NotificationService (false) do not both set use_frameworks!
```

Any way I can fix that or use also `use_frameworks!` for your library ?

Thanks in advance

**Comment by Shahroz16** [comment]
Hey @simontoulouze, thanks for writing in. Did you [configure our plugin](https://customer.io/docs/sdk/expo/getting-started/#configure-the-plugin) to use the same? You will need to set `ios.useFrameworks`  to `static`

**Comment by simontoulouze** [comment]
Hey @Shahroz16, thanks for your reactivity, I indeed missed the fact that there's an `ios.useFrameworks` option in the plugin configuration ! I'll give it a try this morning and keep you in touch !

Thanks very much

**Comment by simontoulouze** [comment]
I still have the same error. My guess is that it's the `NotificationService` app extension which needs the useFrameworks's option

**Comment by simontoulouze** [comment]
You were right @Shahroz16 the option allow me to pass the "Install pods" step 🙏🏻. Now I'm stuck in the "Run fastlane" step with the following error : 
```
▸ The following build commands failed:
▸ ProcessInfoPlistFile /Users/expo/Library/Developer/Xcode/DerivedData/ActualEspacePersonnel-efapmjzrslowkzcnvyahlwkhfokw/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/NotificationService.appex/Info.plist /Users/expo/workingdir/build/app/native/ios/NotificationService/NotificationService-Info.plist (in target 'NotificationService' from project 'App')
```

**Comment by simontoulouze** [comment]
Hi @Shahroz16, any chance you had a look at my error ?
It is building fine on android though, so I'll start my tests with it

**Comment by simontoulouze** [comment]
Hey @Shahroz16, even if the prebuild ends right, its giving me interesting logs : 
```
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/PushService.swift to [...] Error: ENOENT: no such file or directory
```
We are using yarn workspace and `./node_modules/customerio-expo-plugin` should in fact be `../node_modules/customerio-expo-plugin`.
I'll try to figure out which file is doing the copy and patch the path but I'll be very happy if you had some clue about that !

**Comment by simontoulouze** [comment]
Everything's working fine after the lib update !
Thanks for your time @Shahroz16
