### ISSUE TITLE
Android notification getPushPermissionStatus always returns "Granted"

### ISSUE THREAD

**Issue by wanschi** [customerio/customerio-expo-plugin#84]
Hello,

we have a problem with the Push Message Permission request. It always returns "Granted" even if push messages are not allowed. The problem occurs on the simulator. 

On physical devices it returns "NotDetermined" the first time. If I then turn push messages off again in the device settings, it still returns "Granted" the next time.

**Comment by tarikfp** [comment]
This is still happening on `"customerio-expo-plugin": "^2.0.0-beta.1"` and `"customerio-reactnative": "4.2.1"`

I'll have to use following approach as a workaround: 

```
    const firebasePermission = await firebase.messaging().hasPermission()

    const customerioPermission =
      await CustomerIO.pushMessaging.getPushPermissionStatus()

    const isOneOfThemDenied =
      customerioPermission === CioPushPermissionStatus.Denied ||
      firebasePermission === FirebaseMessagingTypes.AuthorizationStatus.DENIED

    console.log({
      firebasePermission,
      customerioPermission,
      isOneOfThemDenied,
    })

```

The console output is: `{"customerioPermission": "GRANTED", "firebasePermission": 0, "isOneOfThemDenied": true}`
