### ISSUE TITLE
Regression regarding monorepos

### ISSUE THREAD

**Issue by simontoulouze** [customerio/customerio-expo-plugin#89]
Hi,

Starting from the beta 11, I can tell there's a regression regarding monorepos handling.
In `customerio-expo-plugin/src/helpers/utils/injectCIOPodfileCode.ts`, there are 2 lines containing hardcoded path to customerio-reactnative lib : 
```
  pod 'customerio-reactnative/apn', :path => '../node_modules/customerio-reactnative'
```
However, for me the path should be :
```
  pod 'customerio-reactnative/apn', :path => '../../node_modules/customerio-reactnative'
```
Those lines lead to the following error during `pod install` : 
```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: There are multiple dependencies with different sources for `customerio-reactnative` in `Podfile`:

- customerio-reactnative (from `../../node_modules/customerio-reactnative`)
- customerio-reactnative/apn (from `../node_modules/customerio-reactnative`)
```

**Comment by Shahroz16** [comment]
Hey @simontoulouze, thank you for reaching out, and apologies for the inconvenience. We are debugging this issue and making sure changing the path doesn't conflict with other things and will push the fix as soon as we can.

**Comment by simontoulouze** [comment]
Thanks @Shahroz16 !
